org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
# KSP 2.2.10-x.y.z ainda usa kotlin.sourceSets para registrar gerados; AGP 9 só aceita
# essa configuracao com este flag. Remover quando bumparmos Kotlin -> 2.3+ e KSP -> 2.3+.
android.disallowKotlinSourceSets=false

kotlin.code.style=official
ksp.incremental=true

passagenexpress.apiToken=LUKnqBOlcsDzilcIsdlGtgqYSffcWPTPryg5Q6Dje8XJ2DiiIXjUSBB8obuN9NBC